### ISSUE TITLE
Parsing errors in arsnova.properties

### ISSUE THREAD

**Issue by pcvolkmer** [thm-projects/arsnova-setuptool#3] opened 2015-10-11 10:24 UTC
Using this setup tool will result in parsing errors within arsnova.properties using current arsnova.properties.example file as base for own configuration:

```
Traceback (most recent call last):
  File "tool.py", line 61, in <module>
    (db, conn) = couchconnection.arsnova_connection("/etc/arsnova/arsnova.properties")
  File "./arsnova-setuptool/couchconnection.py", line 66, in arsnova_connection
    config.readfp(io.BytesIO("[arsnova]" + properties))
  File "/usr/lib64/python2.7/ConfigParser.py", line 324, in readfp
    self._read(fp, filename)
  File "/usr/lib64/python2.7/ConfigParser.py", line 546, in _read
    raise e
ConfigParser.ParsingError: File contains parsing errors: <???>
        [line 229]: 'Allgemeines,Anglistik,Architektur,Bauingenieurwesen,Betriebswirtschaftslehre,Biologie,Chemie,Elektrotechnik,Geographie,Geowissenschaften,Germanistik,Geschichtswissenschaft,Informatik,Kunst,Kunstp\xc3\xa4dagogik,Maschinenbau,Mathematik,Medienwissenschaften,Medizin,Musik,Pharmazie,Physik,Psychologie,Rechtswissenschaften,Stadtplanung,Theaterwissenschaften,Theologie,Vermessungswesen,Volkswirtschaftslehre\n'
```

**Comment by pcvolkmer** [comment] 2015-10-11 10:30
Removing line breaks in line 228 fixed this for me. You should insert a comment into README.md that this must be done if using the provided link to arsnova.properties.example

**Comment by pushPatrol** [comment] 2018-04-03 13:55
This error still shows up. I followed the installation guide and did the changes mentioned here: https://github.com/thm-projects/arsnova-backend/blob/master/src/site/markdown/installation.md#configuration

I get the following error:

> Traceback (most recent call last):
>   File "tool.py", line 61, in <module>
>     (db, conn) = couchconnection.arsnova_connection("/etc/arsnova/arsnova.properties")
>   File "/root/arsnova/arsnova-setuptool/couchconnection.py", line 66, in arsnova_connection
>     config.readfp(io.BytesIO("[arsnova]" + properties))
>   File "/usr/lib/python2.7/ConfigParser.py", line 324, in readfp
>     self._read(fp, filename)
>   File "/usr/lib/python2.7/ConfigParser.py", line 546, in _read
>     raise e
> ConfigParser.ParsingError: File contains parsing errors: <???>
>         [line  7]: '<!DOCTYPE html>\n'
>         [line 134]: '</a>              </li>\n'
>         [line 138]: '</a>              </li>\n'
>         [line 143]: '</a>              </li>\n'
>         [line 148]: '</a>              </li>\n'
>         [line 152]: '</a>              </li>\n'
>         [line 175]: '</form></div>\n'
>         [line 189]: '</header>\n'
>         [line 196]: '</div>\n'
>         [line 259]: '</ul>\n'
>         [line 267]: '</h1>\n'
>         [line 282]: '</a>  </span>\n'
>         [line 290]: '</a>    </span>\n'
>         [line 298]: '</a>  </span>\n'
>         [line 304]: '</a>\n'
>         [line 308]: '</a>\n'
>         [line 313]: '</a>\n'
And so on. I tried to fix all these parsing issues, but the couchconnection.py couldn't find the setting for host, port, db, user and password. So I set them in couchconnection.py directly and could run the tool.py script - finally.

**Comment by dgerhardt** [comment] 2018-07-13 12:26
My guess is this error was caused by copy-and-pasting the content of the configuration file which might have led to unintended charset or indentation changes. I can not reproduce this error when using the `arsnova.properties` files distributed with ARSnova Backend releases.

New lines in property values have to be indented with at least one space. The line break itself has to be escaped with a backslash.

I'm closing this for now. Feel free to reopen but please include an affected config file to reproduce the issue in this case.

**Closed as completed by dgerhardt** 2018-07-13 12:26 UTC
Labels: invalid
