### ISSUE TITLE
Usage for migrations.py

### ISSUE THREAD

**Issue by dhx** [thm-projects/arsnova-setuptool#5] opened 2018-08-28 14:09 UTC
Currently only tool.py is documented in the usage part of the readme.
Is migrations.py not needed normally or what would the effect of not running it be when upgrading arsnova?

**Comment by commana** [comment] 2018-08-28 18:41
Hi @dhx! Thanks for the question! The file `migrations.py` is only for our internal use. Nothing to worry about. :-)

**Comment by dhx** [comment] 2018-08-29 08:35
Hi @commana ! Thanks for your reply, we are currently doing the update to 2.6 and getting lots of errors regarding a missing document, the relevant codeline seems to be: 

https://github.com/thm-projects/arsnova-backend/blob/2.6/src/main/java/de/thm/arsnova/dao/CouchDBDao.java#L568

The only place where I found this arsnova_migrations document else is this migrations.py script but maybe I'm missing something here.

The stacktraces look like this btw.:
``
2018-08-29 10:15:52  WARN pool-2-thread-1 couchdb.Database:381 - Error getting document - not_found missing
2018-08-29 10:15:52 ERROR pool-2-thread-1 dao.CouchDBDao:1362 - Could not retrieve session count.
java.lang.NullPointerException
        at de.thm.arsnova.dao.CouchDBDao.getExpectedMigrationLevel(CouchDBDao.java:569)
        at de.thm.arsnova.dao.CouchDBDao.getDatabase(CouchDBDao.java:550)
        at de.thm.arsnova.dao.CouchDBDao.getStatistics(CouchDBDao.java:1301)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.cache.interceptor.CacheInterceptor$1.invoke(CacheInterceptor.java:52)
        at org.springframework.cache.interceptor.CacheAspectSupport.invokeOperation(CacheAspectSupport.java:342)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:405)
        at org.springframework.cache.interceptor.CacheAspectSupport.execute(CacheAspectSupport.java:324)
        at org.springframework.cache.interceptor.CacheInterceptor.invoke(CacheInterceptor.java:61)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy35.getStatistics(Unknown Source)
        at de.thm.arsnova.services.StatisticsService.refreshStatistics(StatisticsService.java:43)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
``

**Comment by commana** [comment] 2018-08-29 09:34
Looks like the migrations document is missing. You could try and create the document and see what happens. Since I don't know the state of your database, I can only guess which version might work for you. The latest database version is marked as 11, so you could try and create the document with this number:

```json
{ "version": 11 }
```

**Comment by dhx** [comment] 2018-08-29 11:39
@commana thanks for your fast reply, regarding the state of our database, we started with arsnova version 2.1, are currently on 2.4 and are in the process of upgrading to 2.6 now. For every new version we did execute tool.py to create the new db views and so far this was working ok that way. I have never seen the arsnova_migrations view in the database and the usage of this view seemingly was introduced by @dgerhardt in the followin commit in arsnova-backend:

> commit 64f4b4bd28807c4025aab04bd2351fe8bbcd7b2a
> Author: Daniel Gerhardt <code@dgerhardt.net>
> Date:   Sat Jul 7 23:04:31 2018 +0200
> Check database migration level on initialization

I could try to do what you suggest, but to be honest I don't think this is a clean approach and now that I look at it, it seems this migration script also gets mentioned in the migration documentation since v2.5:

https://github.com/thm-projects/arsnova-backend/commit/d59d07aa483ffecf36ce949fa95082d82b3e41fc#diff-dd586a488899280f86e5d714b6e7e475R25

Could you please clarify which version of the migration instructions is correct?

**Comment by dgerhardt** [comment] 2018-08-30 08:57
Hi @dhx!

Sorry for the confusion. `tool.py` and `migrations.py` always have to be run when upgrading to a new minor release. Our [upgrade instructions](https://github.com/thm-projects/arsnova-backend/blob/2.6/src/site/markdown/upgrade.md) are up to date and should be followed.

Starting with ARSnova 2.6 the backend checks the migration level to avoid problems caused by outdated data structures. If the migration level does not match the expected level a warning is logged. Currently, we do not handle the case that no migration level is set (migrations.py has never been run) which is a bug.

**Comment by dgerhardt** [comment] 2018-08-30 11:56
A fix has been pushed to improve error handling in case of a missing migration document.

https://github.com/thm-projects/arsnova-backend/commit/7fb0089ff8d256803c07d4cb1592102e0b33968f

**Comment by dhx** [comment] 2018-08-31 12:51
Hi @dgerhardt thanks for clarifying

**Closed as completed** 2018-10-11 09:23 UTC
